In [1]:
import Model_Util as mu

# -  수치 계산 라이브러리
import numpy as np

In [2]:
mu = mu.Model_Util()

df = mu.data_read("./data/03_농어의_길이_높이_두께_데이터.csv")

perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

train_input, test_input, train_target, test_target = mu.data_split(df, perch_weight, 0.3)
print(train_input, test_input, train_target, test_target)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   length  56 non-null     float64
 1   height  56 non-null     float64
 2   width   56 non-null     float64
dtypes: float64(3)
memory usage: 1.4 KB
[[17.4   4.59  2.94]
 [36.   10.61  6.74]
 [25.    6.44  3.68]
 [40.   11.93  7.11]
 [39.   12.43  7.35]
 [43.   11.93  7.28]
 [22.    5.64  3.52]
 [20.    5.08  2.77]
 [22.    6.11  3.52]
 [24.    7.29  3.72]
 [27.5   7.17  4.34]
 [43.   12.51  7.42]
 [40.   11.73  7.22]
 [24.    6.38  3.82]
 [21.    5.92  3.31]
 [27.5   7.05  4.34]
 [40.   12.38  7.46]
 [32.8  10.03  6.02]
 [26.5   7.17  4.14]
 [36.5  10.88  6.86]
 [13.7   3.53  2.  ]
 [22.7   5.95  3.63]
 [15.    3.82  2.43]
 [37.   10.57  6.37]
 [35.   11.49  7.8 ]
 [28.7   7.59  4.64]
 [23.5   6.28  3.72]
 [39.   11.14  6.  ]
 [21.    5.69  3.56]
 [23.    5.22  3.63]
 [22.    5.52  4.  ]
 [44.   12.49  7.6 ]
 

In [3]:
sample = mu.new_model(train_input, train_target, test_input, test_target)

sample

훈련 결정계수 : 0.9537065271284176, 테스트 결정계수 : 0.8863420836347777, 과적합여부 : 0.0673644434936399
해당 모델은 사용 가능한 모델입니다.
 


In [4]:
poly_sample = mu.poly_model(train_input, train_target, test_input, test_target, 2)

poly_sample

2 차원 모델이 생성되었습니다.
훈련 결정계수 : 0.9898271546307027, 테스트 결정계수 : 0.9713771600629739, 과적합여부 : 0.018449994567728778
해당 모델은 사용 가능한 모델입니다.
 


In [5]:
total_sample = mu.total_model(train_input, train_target, test_input, test_target)

total_sample

기본 모델
훈련 결정계수 : 0.9537065271284176, 테스트 결정계수 : 0.8863420836347777, 과적합여부 : 0.0673644434936399
해당 모델은 사용 가능한 모델입니다.
 
기본 + 표준화 스케일링
훈련 결정계수 : 0.9537065271284176, 테스트 결정계수 : 0.8863420836347777, 과적합여부 : 0.0673644434936399
해당 모델은 사용 가능한 모델입니다.
 
기본 + MinMax 스케일링
훈련 결정계수 : 0.9537065271284176, 테스트 결정계수 : 0.8863420836347775, 과적합여부 : 0.06736444349364012
해당 모델은 사용 가능한 모델입니다.
 
기본 + Robust 스케일링
훈련 결정계수 : 0.9537065271284176, 테스트 결정계수 : 0.8863420836347781, 과적합여부 : 0.06736444349363957
해당 모델은 사용 가능한 모델입니다.
 
폴리노미얼 2 차 모델
2 차원 모델이 생성되었습니다.
훈련 결정계수 : 0.9898271546307027, 테스트 결정계수 : 0.9713771600629739, 과적합여부 : 0.018449994567728778
해당 모델은 사용 가능한 모델입니다.
 
폴리노미얼 3 차 모델
3 차원 모델이 생성되었습니다.
훈련 결정계수 : 0.9961910731490262, 테스트 결정계수 : 0.9454275516675478, 과적합여부 : 0.050763521481478446
해당 모델은 사용 가능한 모델입니다.
 
폴리노미얼 4 차 모델
4 차원 모델이 생성되었습니다.
해당 모델은 사용할 수 없는 모델입니다.
 
폴리노미얼 2 차 + 표준화 스케일링 모델
2 차원 모델이 생성되었습니다.
훈련 결정계수 : 0.9898271546307025, 테스트 결정계수 : 0.97137716006296, 과적합여부 : 0.018449994567742434
해당 모델은 사용 가능한 모델입니다.
 
폴리노